services:
  api:
    build: ./api
    container_name: shorty-ai-api
    ports:
      - "8000:8000"
    volumes:
      - ./generations:/app/generations
      - ./api:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
    env_file:
      - .env

  frontend:
    build: ./frontend
    container_name: shorty-ai-frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_MAX_RECONNECT_ATTEMPTS=10
      - NODE_OPTIONS=--max-old-space-size=2048
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "1.0"

  flux:
    build: ./flux
    container_name: shorty-ai-flux
    ports:
      - "8008:8008"
    volumes:
      - ./models/flux:/app/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ollama:
    image: ollama/ollama:latest
    container_name: shorty-ai-ollama
    ports:
      - "11434:11434"
    volumes:
      - ./models/ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  tts:
    image: ghcr.io/coqui-ai/tts-cpu
    container_name: shorty-ai-tts
    command: tts-server --model_name tts_models/en/ljspeech/glow-tts --use_cuda False
    ports:
      - "5002:5002"
    volumes:
      - ./models/tts:/root/.local/share/tts

networks:
  default:
    name: shorty-ai
